using System;
using System.Collections.Generic;
using System.Text;

namespace HeatApp
{
	public static class IconFont
	{
		public const string Bell = "\ue700";
		public const string Fav = "\ue701";
		public const string Filter = "\ue702";
		public const string Rating = "\ue703";
		public const string Share = "\ue704";
		public const string Search = "\ue705";
		public const string Home = "\ue706";
		public const string Error = "\ue707";
		public const string Cart = "\ue708";
		public const string Back = "\ue709";
		public const string Sort = "\ue70a";
		public const string Dropdown = "\ue70b";
		public const string Rating1 = "\ue70c";
		public const string List = "\ue70d";
		public const string Account = "\ue70e";
		public const string Facebook = "\ue70f";
		public const string Hide = "\ue710";
		public const string Show = "\ue711";
		public const string UpArrow = "\ue712";
		public const string Photo = "\ue713";
		public const string Group = "\ue714";
		public const string More1 = "\ue715";
		public const string Delete = "\ue716";
		public const string Sent = "\ue717";
		public const string VideoFill = "\ue718";
		public const string More = "\ue719";
		public const string Next = "\ue71a";
		public const string Viewed = "\ue71b";
		public const string Phone = "\ue71c";
		public const string Image = "\ue71d";
		public const string Attach = "\ue71e";
		public const string Send = "\ue71f";
		public const string NewMessage = "\ue720";
		public const string VideoLine = "\ue721";
		public const string Audio = "\ue722";
		public const string ContactFill = "\ue723";
		public const string Close = "\ue724";
		public const string Mail = "\ue725";
		public const string Album = "\ue726";
		public const string Edit = "\ue727";
		public const string ArrowRight = "\ue728";
		public const string MapPin = "\ue729";
		public const string PhoneFill = "\ue72a";
		public const string Setting = "\ue72b";
		public const string Help = "\ue72c";
		public const string Ok = "\ue72d";
		public const string BurgerMenu = "\ue72e";
		public const string BookmarkFill = "\ue72f";
		public const string Add = "\ue730";
		public const string Photo1 = "\ue731";
		public const string Favourite = "\ue732";
		public const string Category = "\ue733";
		public const string Bookmark_Line = "\ue734";
		public const string Facebook1 = "\ue735";
		public const string Offer = "\ue736";
		public const string Termsofservice = "\ue737";
		public const string Packed = "\ue738";
		public const string MyOrders = "\ue739";
		public const string Document = "\ue73a";
		public const string Message = "\ue73b";
		public const string Cartwaiting = "\ue73c";
		public const string PaymentFailed = "\ue73d";
		public const string LinkAccount = "\ue73e";
		public const string ChangePassword = "\ue73f";
		public const string Shipped = "\ue740";
		public const string Delivered = "\ue741";
		public const string Calendar = "\ue742";
		public const string Flashsale = "\ue743";
		public const string Music = "\ue744";
		public const string FAQs = "\ue745";
		public const string PrivacyPolicy = "\ue746";
		public const string Logout = "\ue747";
		public const string Whatsapp = "\ue748";
		public const string Twitter = "\ue749";
		public const string FileExplorer = "\ue74a";
		public const string Snack = "\ue74b";
		public const string Gym = "\ue74c";
		public const string GooglePlus = "\ue74d";
		public const string Lunch = "\ue74e";
		public const string Dinner = "\ue74f";
		public const string Breakfast = "\ue750";
		public const string OrganizationWorkshop = "\ue751";
		public const string Reminder = "\ue752";
		public const string HTMLCode = "\ue753";
	}
}
